clear

% =====================================
%         Load in the solution
F = load('./../../stokeswavedata/bdint_N801_ep0.05.mat');
solbdint = F.solbdint;
F = load('./../../stokeswavedata/series_N100_ep0.05.mat');
solseries = F.solseries;
F = load('./../../stokeswavedata/meshdatbd_ep0.05.mat');
meshdatbd = F.meshdatbd;
% =====================================


% =====================================
%            Path input

% Define the path manually 
% pm = 1i*1e-3;
pm = 1i*1e-10;
path_n1_n1 = [-0.4 + pm, ...
        -0.4 + 1i, ...
        0.4 + 1i, ...
        0.4 + pm, ...
        NaN, ...
        0.4 - pm, ...
        0.4 - 1i, ...
        -0.4 - 1i, ...
        -0.4 - pm];
path_n1_0 = [-0.4 + pm, ...
        -0.4 + 1i, ...
        0.4 + 1i, ...
        0.4 + pm, ...
        NaN, ...
        0.4 - pm, ...
        0.4 - 0.2i, ...
        -0.4 - 0.2i, ...
        -0.4 - pm];
path_n1= [-0.4 + pm, ...
        -0.4 + 1i, ...
        0.4 + 1i, ...
        0.4 + pm];
path_n0 = [-0.4 + pm, ...
        -0.4 + 0.2i, ...
        0.4 + 0.2i, ...
        0.4 + pm];  

path = path_n1;


[f, x, y] = bdint_path_solve1(path, solbdint, solseries, meshdatbd);
z = x + 1i*y;

%%

figure(1); figshift; hold all
plot3(real(f),imag(f),real(z), 'k-', 'LineWidth', 2);
xlabel('\phi'); ylabel('\psi'); zlabel('Re(z)');
